# Can You Roll the Dungeon Master’s Dice? (2024.01.12)

link: https://thefiddler.substack.com/p/can-you-roll-the-dungeon-masters

## I. Puzzle

Two people have each a bag of six “DnD dice” (d4, d6, d8, d10, d12, and d20). Here, “dX” refers to a die with X faces, numbered from 1 to X, each with an equally likely probability of being rolled. Both people randomly pick one die from their respective bags and then roll them at the same time. 

What’s the probability that both players roll the same number, whether or not they happened to pick the same kind of die?

# II. Solution

Calculate the probabilities for all dice and every number:

In [71]:
import pandas as pd

dice = [4, 6, 8 ,10, 12, 20]
n_dice = len(dice)

die_values = [i for i in range(1,21)]

df = pd.DataFrame(0, index=dice, columns=die_values).astype(float)

for row in range(n_dice):
	sides = df.index[row]
	for column in range(sides):
		df.at[sides,column+1] = 1/sides

display(df.round(3))

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
4,0.250,0.250,0.250,0.250,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,0.167,0.167,0.167,0.167,0.167,0.167,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,0.100,0.100,0.100,0.100,0.100,0.100,0.100,0.100,0.100,0.100,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.083,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
20,0.050,0.050,0.050,0.050,0.050,0.050,0.050,0.050,0.050,0.050,0.050,0.050,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05

Calculate the probability of all numbers for one player or two players (at the same time):

In [62]:
df_result = pd.DataFrame(df.sum()/n_dice, columns=['P for 1 player'])
df_result['P for 2 players'] = df_result['P for 1 player']**2
df_result.round(4) # probability for one or two players to have a number

    P for 1 player  P for 2 players
1           0.1292           0.0167
2           0.1292           0.0167
3           0.1292           0.0167
4           0.1292           0.0167
5           0.0875           0.0077
6           0.0875           0.0077
7           0.0597           0.0036
8           0.0597           0.0036
9           0.0389           0.0015
10          0.0389           0.0015
11          0.0222           0.0005
12          0.0222           0.0005
13          0.0083           0.0001
14          0.0083           0.0001
15          0.0083           0.0001
16          0.0083           0.0001
17          0.0083           0.0001
18          0.0083           0.0001
19          0.0083           0.0001
20          0.0083           0.0001

In [70]:
print (f'The probability that both players have the same number is {sum(df_result['P for 2 players'])*100:.3f}%.')

The probability that both players have the same number is 9.375%.

## III. Monte-Carlo-Simulation

Let us check the result with a simulation.

In [69]:
import random as rd

rounds = 1000000
dice = [4, 6, 8 ,10, 12, 20]

def pick_and_roll(dice):
	return rd.randint(1,dice[rd.randint(0,5)])

counter = 0

for r in range(rounds):
	if pick_and_roll(dice) == pick_and_roll(dice):
		counter += 1

print(f'The probabilty that both players have the same number is {counter/rounds*100:.2f}%.')

The probabilty that both players have the same number is 9.36%.